### ISSUE TITLE
Lost new_model.bin.trainables.syn1neg.npy in the feature envy project

### ISSUE THREAD

**Issue by Ghostiiian** [liuhuigmail/DeepSmellDetection#1]
When I try to run `trainCNN.py` in the https://github.com/liuhuigmail/DeepSmellDetection/blob/master/feature%20envy/Algorithm/trainCNN.py#L115 , it says No such file or directory: 'new_model.bin.trainables.syn1neg.npy' 

Error message:
```
Traceback (most recent call last):
  File "F:/featureenvy/Algorithm/trainCNN.py", line 219, in <module>
    train()
  File "F:/featureenvy/Algorithm/trainCNN.py", line 102, in train
    embedding_model = word2vec.Word2Vec.load(basepath + "new_model.bin")
  File "C:\Users\fme\anaconda3\envs\tensorflow3\lib\site-packages\gensim\models\word2vec.py", line 1141, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "C:\Users\fme\anaconda3\envs\tensorflow3\lib\site-packages\gensim\models\base_any2vec.py", line 1230, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "C:\Users\fme\anaconda3\envs\tensorflow3\lib\site-packages\gensim\models\base_any2vec.py", line 602, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "C:\Users\fme\anaconda3\envs\tensorflow3\lib\site-packages\gensim\utils.py", line 436, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "C:\Users\fme\anaconda3\envs\tensorflow3\lib\site-packages\gensim\utils.py", line 467, in _load_specials
    getattr(self, attrib)._load_specials(cfname, mmap, compress, subname)
  File "C:\Users\fme\anaconda3\envs\tensorflow3\lib\site-packages\gensim\utils.py", line 478, in _load_specials
    val = np.load(subname(fname, attrib), mmap_mode=mmap)
  File "C:\Users\fme\anaconda3\envs\tensorflow3\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'F:/featureenvy/Data/data/new_model.bin.trainables.syn1neg.npy'

Process finished with exit code 1
```

Environment: python 3.6 and tensorflow 2.2

**Comment by TyrantJin** [comment]
@Ghostiiian I have uploaded the file in [https://github.com/liuhuigmail/DeepSmellDetection/tree/master/feature%20envy/Algorithm](url)

**Comment by Ghostiiian** [comment]
@TyrantJin It seems still needs `new_model.bin.wv.vectors.npy` to run it, error message:

```
Traceback (most recent call last):
  File "trainCNN1.py", line 220, in <module>
    train()
  File "trainCNN1.py", line 102, in train
    embedding_model = word2vec.Word2Vec.load('F:/featureenvy/Algorithm/new_model.bin')
  File "C:\Users\fme\anaconda3\lib\site-packages\gensim\models\word2vec.py", line 1141, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "C:\Users\fme\anaconda3\lib\site-packages\gensim\models\base_any2vec.py", line 1230, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "C:\Users\fme\anaconda3\lib\site-packages\gensim\models\base_any2vec.py", line 602, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "C:\Users\fme\anaconda3\lib\site-packages\gensim\utils.py", line 436, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "C:\Users\fme\anaconda3\lib\site-packages\gensim\utils.py", line 467, in _load_specials
    getattr(self, attrib)._load_specials(cfname, mmap, compress, subname)
  File "C:\Users\fme\anaconda3\lib\site-packages\gensim\utils.py", line 478, in _load_specials
    val = np.load(subname(fname, attrib), mmap_mode=mmap)
  File "C:\Users\fme\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'F:/featureenvy/Algorithm/new_model.bin.wv.vectors.npy'
```

**Comment by liuhuigmail** [comment]
----It seems still needs new_model.bin.wv.vectors.npy to run it------
This document is availabe in the same location, i.e., [https://github.com/liuhuigmail/DeepSmellDetection/tree/master/feature%20envy/Algorithm]

**Comment by Ghostiiian** [comment]
Thanks, my fault
